package edu.brandeis.bostonaccessibleroutes.ws.RESTmodel.vo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Dec 01 04:24:00 EST 2016
// ---------------------------------------------------------------------
public interface AprRoadconditionView extends ViewObject {
    long saveRoadConditionWS(int localId, String appCode, int roadCondition, String username, String timestamp,
                             String image, String voice, String comment, double gpsLong, double gpsLat);
}

