package edu.brandeis.bostonaccessibleroutes.ws.RESTmodel.vo;


import edu.brandeis.bostonaccessibleroutes.ws.RESTmodel.vo.common.AprRoadconditionView;

import java.math.BigDecimal;

import java.sql.Timestamp;

import java.util.Date;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 30 15:58:12 EST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AprRoadconditionViewImpl extends ViewObjectImpl implements AprRoadconditionView {
    /**
     * This is the default constructor (do not remove).
     */
    public AprRoadconditionViewImpl() {
    }
    public long saveRoadConditionWS(int localId,String appCode,int roadCondition,String username,String timestamp,String image,String voice,String comment,double gpsLong,double gpsLat ) {
           
            AprRoadconditionViewRowImpl row = (AprRoadconditionViewRowImpl) createRow();
            row.setLocalId(new BigDecimal(localId));
            row.setAppCode(appCode);
            row.setRoadConditionId(new BigDecimal(roadCondition));
            row.setUsername(username);
            row.setTimeStamp(new Timestamp((new Date()).getTime()));
            row.setImageUrl(image);
            row.setVoiceUrl(voice);
            row.setCmnt(comment);
            row.setGpsLong(new BigDecimal(gpsLong));
            row.setGpsLat(new BigDecimal(gpsLat));
            insertRow(row);
            getDBTransaction().commit();
            return row.getId().getValue();
            
        }
}

