package edu.brandeis.bostonaccessibleroutes.ws.RESTmodel.vo;

import edu.brandeis.bostonaccessibleroutes.ws.RESTmodel.eo.AprRoadconditionImpl;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.domain.DBSequence;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 30 15:58:11 EST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AprRoadconditionViewRowImpl extends ViewRowImpl {

    public static final int ENTITY_APRROADCONDITION = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Id,
        LocalId,
        AppCode,
        Username,
        TimeStamp,
        RoadConditionId,
        ImageUrl,
        VoiceUrl,
        Cmnt,
        GpsLong,
        GpsLat;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int ID = AttributesEnum.Id.index();
    public static final int LOCALID = AttributesEnum.LocalId.index();
    public static final int APPCODE = AttributesEnum.AppCode.index();
    public static final int USERNAME = AttributesEnum.Username.index();
    public static final int TIMESTAMP = AttributesEnum.TimeStamp.index();
    public static final int ROADCONDITIONID = AttributesEnum.RoadConditionId.index();
    public static final int IMAGEURL = AttributesEnum.ImageUrl.index();
    public static final int VOICEURL = AttributesEnum.VoiceUrl.index();
    public static final int CMNT = AttributesEnum.Cmnt.index();
    public static final int GPSLONG = AttributesEnum.GpsLong.index();
    public static final int GPSLAT = AttributesEnum.GpsLat.index();

    /**
     * This is the default constructor (do not remove).
     */
    public AprRoadconditionViewRowImpl() {
    }

    /**
     * Gets AprRoadcondition entity object.
     * @return the AprRoadcondition
     */
    public AprRoadconditionImpl getAprRoadcondition() {
        return (AprRoadconditionImpl) getEntity(ENTITY_APRROADCONDITION);
    }

    /**
     * Gets the attribute value for ID using the alias name Id.
     * @return the ID
     */
    public DBSequence getId() {
        return (DBSequence) getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as attribute value for ID using the alias name Id.
     * @param value value to set the ID
     */
    public void setId(DBSequence value) {
        setAttributeInternal(ID, value);
    }

    /**
     * Gets the attribute value for LOCAL_ID using the alias name LocalId.
     * @return the LOCAL_ID
     */
    public BigDecimal getLocalId() {
        return (BigDecimal) getAttributeInternal(LOCALID);
    }

    /**
     * Sets <code>value</code> as attribute value for LOCAL_ID using the alias name LocalId.
     * @param value value to set the LOCAL_ID
     */
    public void setLocalId(BigDecimal value) {
        setAttributeInternal(LOCALID, value);
    }

    /**
     * Gets the attribute value for APP_CODE using the alias name AppCode.
     * @return the APP_CODE
     */
    public String getAppCode() {
        return (String) getAttributeInternal(APPCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for APP_CODE using the alias name AppCode.
     * @param value value to set the APP_CODE
     */
    public void setAppCode(String value) {
        setAttributeInternal(APPCODE, value);
    }

    /**
     * Gets the attribute value for USERNAME using the alias name Username.
     * @return the USERNAME
     */
    public String getUsername() {
        return (String) getAttributeInternal(USERNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for USERNAME using the alias name Username.
     * @param value value to set the USERNAME
     */
    public void setUsername(String value) {
        setAttributeInternal(USERNAME, value);
    }

    /**
     * Gets the attribute value for TIME_STAMP using the alias name TimeStamp.
     * @return the TIME_STAMP
     */
    public Timestamp getTimeStamp() {
        return (Timestamp) getAttributeInternal(TIMESTAMP);
    }

    /**
     * Sets <code>value</code> as attribute value for TIME_STAMP using the alias name TimeStamp.
     * @param value value to set the TIME_STAMP
     */
    public void setTimeStamp(Timestamp value) {
        setAttributeInternal(TIMESTAMP, value);
    }

    /**
     * Gets the attribute value for ROAD_CONDITION_ID using the alias name RoadConditionId.
     * @return the ROAD_CONDITION_ID
     */
    public BigDecimal getRoadConditionId() {
        return (BigDecimal) getAttributeInternal(ROADCONDITIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for ROAD_CONDITION_ID using the alias name RoadConditionId.
     * @param value value to set the ROAD_CONDITION_ID
     */
    public void setRoadConditionId(BigDecimal value) {
        setAttributeInternal(ROADCONDITIONID, value);
    }

    /**
     * Gets the attribute value for IMAGE_URL using the alias name ImageUrl.
     * @return the IMAGE_URL
     */
    public String getImageUrl() {
        return (String) getAttributeInternal(IMAGEURL);
    }

    /**
     * Sets <code>value</code> as attribute value for IMAGE_URL using the alias name ImageUrl.
     * @param value value to set the IMAGE_URL
     */
    public void setImageUrl(String value) {
        setAttributeInternal(IMAGEURL, value);
    }

    /**
     * Gets the attribute value for VOICE_URL using the alias name VoiceUrl.
     * @return the VOICE_URL
     */
    public String getVoiceUrl() {
        return (String) getAttributeInternal(VOICEURL);
    }

    /**
     * Sets <code>value</code> as attribute value for VOICE_URL using the alias name VoiceUrl.
     * @param value value to set the VOICE_URL
     */
    public void setVoiceUrl(String value) {
        setAttributeInternal(VOICEURL, value);
    }

    /**
     * Gets the attribute value for CMNT using the alias name Cmnt.
     * @return the CMNT
     */
    public String getCmnt() {
        return (String) getAttributeInternal(CMNT);
    }

    /**
     * Sets <code>value</code> as attribute value for CMNT using the alias name Cmnt.
     * @param value value to set the CMNT
     */
    public void setCmnt(String value) {
        setAttributeInternal(CMNT, value);
    }

    /**
     * Gets the attribute value for GPS_LONG using the alias name GpsLong.
     * @return the GPS_LONG
     */
    public BigDecimal getGpsLong() {
        return (BigDecimal) getAttributeInternal(GPSLONG);
    }

    /**
     * Sets <code>value</code> as attribute value for GPS_LONG using the alias name GpsLong.
     * @param value value to set the GPS_LONG
     */
    public void setGpsLong(BigDecimal value) {
        setAttributeInternal(GPSLONG, value);
    }

    /**
     * Gets the attribute value for GPS_LAT using the alias name GpsLat.
     * @return the GPS_LAT
     */
    public BigDecimal getGpsLat() {
        return (BigDecimal) getAttributeInternal(GPSLAT);
    }

    /**
     * Sets <code>value</code> as attribute value for GPS_LAT using the alias name GpsLat.
     * @param value value to set the GPS_LAT
     */
    public void setGpsLat(BigDecimal value) {
        setAttributeInternal(GPSLAT, value);
    }
}

