package edu.brandeis.bostonaccessibleroutes.ws.RESTmodel.eo;

import edu.brandeis.bostonaccessibleroutes.ws.RESTmodel.vo.AprRoadconditionViewImpl;

import edu.brandeis.bostonaccessibleroutes.ws.RESTmodel.vo.AprRoadconditionViewRowImpl;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.server.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 30 15:58:50 EST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class APRWSAppModuleImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public APRWSAppModuleImpl() {
    }
public long saveRoadConditionWS(int localId,String appCode,int roadCondition,String username,java.util.Date timestamp,String image,String voice,String comment,double gpsLong,double gpsLat ) {
        AprRoadconditionViewImpl aprRoadconditionView1 = getAprRoadconditionView1();
        AprRoadconditionViewRowImpl row = (AprRoadconditionViewRowImpl) aprRoadconditionView1.createRow();
        row.setLocalId(new BigDecimal(localId));
        row.setAppCode(appCode);
        row.setRoadConditionId(new BigDecimal(roadCondition));
        row.setUsername(username);
        row.setTimeStamp(new Timestamp(timestamp.getTime()));
        row.setImageUrl(image);
        row.setVoiceUrl(voice);
        row.setCmnt(comment);
        row.setGpsLong(new BigDecimal(gpsLong));
        row.setGpsLat(new BigDecimal(gpsLat));
        aprRoadconditionView1.insertRow(row);
        getDBTransaction().commit();
        return row.getId().getValue();
        
    }
    /**
     * Container's getter for AprRoadconditionView1.
     * @return AprRoadconditionView1
     */
    public AprRoadconditionViewImpl getAprRoadconditionView1() {
        return (AprRoadconditionViewImpl) findViewObject("AprRoadconditionView1");
    }
}

